### ISSUE TITLE
[Bug] User copyWith constructor does not copy existing fields from old object 

### ISSUE THREAD

**Issue by tusharlock10** [flyerhq/flutter_chat_types#24]
Consider the code - 
```
user = types.User(
    id: Uuid().v4(),
    firstName: "Test",
    imageUrl: "https:// .... ", 
);

updatedUser = user.copyWith(
    lastSeen: DateTime.now()
);
```
The newUser contains only id and lastSeen fields. Other fields are null.

Expectation - 
updatedUser should also contain all existing non-null fields from the previous User object

**Comment by demchenkoalex** [comment]
Thanks for the report! Will be fixed in a new version together with a Flutter 3 upgrade.
