### ISSUE TITLE
Private constructors

### ISSUE THREAD

**Issue by rippan** [flyerhq/flutter_chat_types#29]
Hi,

I'm using your plugin and added some attributes to User and Room by extending them. However I can't do that now with the new update since the constructors are private. Only the factory constructor is available. 

Br,
Rippan

**Comment by demchenkoalex** [comment]
Hello!

This was never intended and probably was supported accidentally. We needed to do the change to make `copyWith` work correctly and I don't know if I can do anything here (if there is a quick fix that I don't see feel free to make a PR). The correct way of storing additional attributes in any class (User, Room, messages etc) is to use `metadata` field.
