### ISSUE TITLE
Definition of all atributes posibilities

### ISSUE THREAD

**Issue by pablourkiza** [flyerhq/flutter_chat_types#31]
Hello,

I am wondering if there is any file where each atribute is described. For example, I cannot find what an "agent" role for a room is.

Congratulations, good library, Thanks,

Pablo

**Comment by demchenkoalex** [comment]
Hello, no there is no file, and I think types should be self-explanatory. Roles have no effect, most of the types are just placeholders for different implementations, for example "agent" was added in case someone will want to make a chat support room.

**Comment by pablourkiza** [comment]
Hello, many thanks for your feedback. And what is "channel" for room type? Thanks!

**Comment by demchenkoalex** [comment]
Read-only room, like you subscribe to the channel and only read messages from someone

**Comment by pablourkiza** [comment]
What I imagined. Thanks!
