### ISSUE TITLE
copyWith throws TypeError when built for web

### ISSUE THREAD

**Issue by phr4fh** [flyerhq/flutter_chat_types#39]
Hi, thanks for your awesome library! I just encountered a bug that was extremely difficult to trace and I don't know what happens here exactly...

I'm using Message.copyWith in the process of creating my messages to diplay them in a chat UI. On Flutter Web, the following code throws a TypeError:

```
   flyerTypes.Message method1(flyerTypes.Message raw) {
    return raw.copyWith(id: "msg001"); // this throws TypeError: Instance of '_Type': type '_Type' is not a subtype of type 'Map<String, dynamic>?'
   }
```
I fixed it by passing **metadata** as parameter to copyWith:
```
   flyerTypes.Message method2(flyerTypes.Message raw) {
    return raw.copyWith(id: "msg002", metadata: raw.metadata); // this works fine
   }
```

- It is also fine (both ways) on Android, iOS and Windows.
- It is also fine when I debug it locally in the browser.
- Only when built and deployed to docker, it results in `TypeError: Instance of '_Type': type '_Type' is not a subtype of type 'Map<String, dynamic>?'`

Could it be something to do with` dynamic metadata = _Unset` in the [copyWith implementation](https://github.com/flyerhq/flutter_chat_types/blob/main/lib/src/messages/text_message.dart#L143)? Maybe minifying to JS optimizes the _Unset type away?

**Comment by demchenkoalex** [comment]
Hello. Oh man this looks hard haha.. the dynamic unset approach is the only way to make `copyWith` work with values and nulls without resetting all fields of the message. I already re-written this library for my upcoming `v2` implementation and I used the same approach, cause there is literally no alternative. I wonder what can I even do here 🤔

**Comment by phr4fh** [comment]
Is something like the [copy_with_extension](https://pub.dev/packages/copy_with_extension) not an option?

**Comment by demchenkoalex** [comment]
did not know about this package, let me test it :)

**Comment by demchenkoalex** [comment]
For the `v2` types I was able to use freezed to generate pretty much everything, my final types would look something like this:

```dart
import 'package:freezed_annotation/freezed_annotation.dart';

import 'epoch_date_time_converter.dart';
import 'link_preview.dart';

part 'message.freezed.dart';
part 'message.g.dart';

@Freezed(unionKey: 'type', fallbackUnion: 'unsupported')
sealed class Message with _$Message {
  const factory Message.text({
    required String id,
    required String senderId,
    @EpochDateTimeConverter() required DateTime timestamp,
    Map<String, dynamic>? metadata,
    required String text,
    LinkPreview? linkPreview,
  }) = TextMessage;

  const factory Message.image({
    required String id,
    required String senderId,
    @EpochDateTimeConverter() required DateTime timestamp,
    Map<String, dynamic>? metadata,
    required String source,
    String? thumbhash,
    String? blurhash,
    double? width,
    double? height,
  }) = ImageMessage;

  const factory Message.unsupported({
    required String id,
    required String senderId,
    @EpochDateTimeConverter() required DateTime timestamp,
    Map<String, dynamic>? metadata,
  }) = UnsupportedMessage;

  factory Message.fromJson(Map<String, dynamic> json) =>
      _$MessageFromJson(json);
}
```
